name: build-mkdocs
run-name: build-mkdocs

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '0 */4 * * *'

permissions:
  contents: write

jobs:
  mkdocs-jobs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: job-built
      run: ./build.sh
    - name: job-commit
      uses: stefanzweifel/git-auto-commit-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        commit_message: 'update docs'
        commit_options: '--no-verify'
        file_pattern: '*'
        status_options: '--untracked-files=no'
        skip_fetch: true
        skip_checkout: true
